language: node_js
node_js:
  - lts/* # latest LTS Node.js release
cache: npm
branches:
  only:
    - master # build master branch only
    - /v\d+\.\d+\.\d+/ # build tagged commits
script:
  - npm run build
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc 2> /dev/null
deploy:
  provider: script
  script: "npm run release:deploy"
  skip_cleanup: true
  on:
    tags: true
